image: ubuntu:18.04

before_script:
  - apt update
  - apt -y full-upgrade

test:
  script:
  - apt update
  - apt install -y doxygen graphviz
  - cd docs
  - doxygen Doxyfile
  except:
  - master

build-linux:
  stage: build
  script: 
  - apt install -y make gcc
  - make -j4
  artifacts:
    paths:
      - bin
    expire_in: 1 week

build-windows:
  stage: build
  script: 
  - apt install -y make gcc-mingw-w64-x86-64
  - make -j4 CC=/usr/bin/x86_64-w64-mingw32-gcc TARGET=ProjetS6-MarcNGUYEN-ThomasLARDY.exe
  artifacts:
    paths:
      - bin
    expire_in: 1 week

pages:
  script: 
  - apt update
  - apt install -y doxygen graphviz
  - cd docs
  - doxygen Doxyfile
  - mv webdoc/html/ ../public/
  artifacts:
    paths:
    - public
  only:
  - master
