image: alpine:latest
stages:
  - test
  - build
  - pages
  - deploy

pages:
  image: alpine:latest
  stage: pages
  script: 
  - apk add doxygen graphviz ghostscript-fonts
  - doxygen Doxyfile
  - mv webdoc/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master
  - gitlab-ci-test

build-linux:
  image: alpine:latest
  stage: build
  script: 
  - apk add build-base
  - make -j4
  - cp bin/* ./ProjetS6-MarcNGUYEN-ThomasLARDY
  artifacts:
    paths:
      - ProjetS6-MarcNGUYEN-ThomasLARDY
    expire_in: 1 week
  only:
  - master
  - gitlab-ci-test

build-windows:
  image: ubuntu:latest
  stage: build
  script: 
  - apt update
  - apt install -y make gcc-mingw-w64-x86-64*
  - make -j4 CC=/usr/bin/x86_64-w64-mingw32-gcc TARGET=ProjetS6-MarcNGUYEN-ThomasLARDY.exe
  - cp bin/* ./ProjetS6-MarcNGUYEN-ThomasLARDY.exe
  artifacts:
    paths:
      - ProjetS6-MarcNGUYEN-ThomasLARDY.exe
    expire_in: 1 week
  only:
  - master
  - gitlab-ci-test

test-docs:
  image: alpine:latest
  stage: test
  script:
  - apk add doxygen graphviz ghostscript-fonts
  - doxygen Doxyfile

test-build-linux:
  image: alpine:latest
  stage: build
  script:
  - apk add build-base
  - make -j4
  except:
  - master
  - gitlab-ci-test

test-build-windows:
  image: ubuntu:latest
  stage: build
  script:
  - apt update
  - apt install -y make gcc-mingw-w64-x86-64
  - make -j4 CC=/usr/bin/x86_64-w64-mingw32-gcc TARGET=ProjetS6-MarcNGUYEN-ThomasLARDY.exe
  except:
  - master
  - gitlab-ci-test

unit-tests-linux:
  image: alpine:latest
  stage: test
  script:
  - apk add build-base
  - make tests -j4
  - for file in bin/*; do $file; done

unit-tests-windows:
  image: ubuntu:latest
  stage: test
  script:
  - apt update
  - apt install -y make gcc-mingw-w64-x86-64
  - make all -j4 CC=/usr/bin/x86_64-w64-mingw32-gcc  # TODO: run on linux, windows bin

production:
  type: deploy
  dependencies:
    - build-windows
    - build-linux
    - pages
    - unit-tests-linux
    - unit-tests-windows
  script:
    - echo "0"
  artifacts:
    paths:
      - ./
    expire_in: 1 year
  only:
  - tags
  - gitlab-ci-test
