image: ubuntu:latest

stages:
  - pages
  - build
  - test

before_script:
  - apt update

pages:
  stage: pages
  script: 
  - apt install -y doxygen graphviz
  - doxygen Doxyfile
  - mv webdoc/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master

build-linux:
  stage: build
  script: 
  - apt install -y make gcc
  - make -j4
  artifacts:
    paths:
      - bin
    expire_in: 1 week

build-windows:
  stage: build
  script: 
  - apt install -y make gcc-mingw-w64-x86-64
  - make -j4 CC=/usr/bin/x86_64-w64-mingw32-gcc TARGET=ProjetS6-MarcNGUYEN-ThomasLARDY.exe
  artifacts:
    paths:
      - bin
    expire_in: 1 week

test-docs:
  stage: test
  script:
  - apt install -y doxygen graphviz
  - doxygen Doxyfile

unit-tests-linux:
  stage: test
  script:
  - apt install -y make gcc
  - cd tests
  - make -j4
  - for file in bin/*; do $file; done

unit-tests-windows:
  stage: test
  script:
  - apt install -y make gcc-mingw-w64-x86-64
  - cd tests
  - make -j4 CC=/usr/bin/x86_64-w64-mingw32-gcc  # TODO: run on linux, windows bin

