image: ubuntu:latest

stages:
  - pages
  - build
  - test

before_script:
  - apt update

pages:
  stage: pages
  script: 
  - apt install -y doxygen graphviz
  - doxygen Doxyfile
  - mv webdoc/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master

build-linux:
  stage: build
  script: 
  - apt install -y make gcc
  - make -j4
  - cp bin/ProjetS6-MarcNGUYEN-ThomasLARDY ./ProjetS6-MarcNGUYEN-ThomasLARDY
  artifacts:
    paths:
      - ProjetS6-MarcNGUYEN-ThomasLARDY
    expire_in: 1 week
  only:
  - master

build-windows:
  stage: build
  script: 
  - apt install -y make gcc-mingw-w64-x86-64*
  - make -j4 CC=/usr/bin/x86_64-w64-mingw32-gcc TARGET=ProjetS6-MarcNGUYEN-ThomasLARDY.exe
  - cp bin/ProjetS6-MarcNGUYEN-ThomasLARDY.exe ./ProjetS6-MarcNGUYEN-ThomasLARDY.exe
  artifacts:
    paths:
      - ProjetS6-MarcNGUYEN-ThomasLARDY.exe
    expire_in: 1 week
  only:
  - master

test-docs:
  stage: test
  script:
  - apt install -y doxygen graphviz
  - doxygen Doxyfile

test-build-linux:
  stage: build
  script:
  - apt install -y make gcc
  - make -j4
  except:
  - master

test-build-windows:
  stage: build
  script:
  - apt install -y make gcc-mingw-w64-x86-64
  - make -j4 CC=/usr/bin/x86_64-w64-mingw32-gcc TARGET=ProjetS6-MarcNGUYEN-ThomasLARDY.exe
  except:
  - master

unit-tests-linux:
  stage: test
  script:
  - apt install -y make gcc
  - make tests -j4
  - for file in bin/*; do $file; done

unit-tests-windows:
  stage: test
  script:
  - apt install -y make gcc-mingw-w64-x86-64
  - make all -j4 CC=/usr/bin/x86_64-w64-mingw32-gcc  # TODO: run on linux, windows bin

